baseurl = "https://auta-tks.github.io/portfolio/"
languageCode = "ja" #日本語を指定
title = "盆地至上主義" #タイトルを指定
publishDir = "docs"  # この行を追加
canonifyurls = true
[taxonomies]
tag = "tags"
category = "categories"
